version: "3.5"

services:
  # put service name in mysql host configure in application.properties
  mysql-db:
    image: mysql:latest
    #    image: mysql:5.7.22
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecomDashApp
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      - jarok-network
    # command login to mysql server
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysqldata:/docker-entrypoint-initdb.d # init database via mapping source has sql file
      - C:/mysql_data/ecomdashapp:/var/lib/mysql # mapping mysql data to local machine

  spring-boot-docker:
    restart: on-failure
    image: springio/demo-docker
    container_name: spring-docker
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - jarok-network
    depends_on:
      - mysql-db
    ports:
      - "8080"

  nginx:
    container_name: web_nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring-boot-docker
    networks:
      - jarok-network

networks:
  jarok-network:
    name: jarok-global-net
    driver: bridge