--- 
app: 
  auth: 
    Uris: 
      - "http://localhost:3000/oauth2/redirect"
      - "myandroidapp://oauth2/redirect"
      - "myiosapp://oauth2/redirect"
    oauth2: authorizedRedirect
    tokenExpirationMsec: 864000000
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
spring: 
  datasource:
    url: jdbc:mysql://mysql-db:3306/ecomDashApp?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    password: root
    username: root
  environment: production
  jpa: 
    hibernate: 
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  name: prod-YAML
  profiles: prod
  security: 
    oauth2: 
      client: 
        registration: 
          facebook: 
            client-id: 121189305185277
            client-secret: 42ffe5aa7379e8326387e0fe16f34132
            redirect-uri-template: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: 
              - email
              - public_profile
          github: 
            client-id: d3e47fc2ddd966fa4352
            client-secret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirect-uri-template: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: 
              - "user:email"
              - "read:user"
          google: 
            client-id: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            client-secret: tWZKVLxaD_ARWsriiiUFYoIk
            redirect-uri-template: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: 
              - email
              - profile
        provider: 
            authorization-uri: "https://www.facebook.com/v3.0/dialog/oauth"
            facebook: ~
            tokenUri: "https://graph.facebook.com/v3.0/oauth/access_token"
            user-info-uri: "https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)"
  thymeleaf: 
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: "classpath:/templates/"
    suffix: .html
